/**
 * Lightweight RAG service for the docs chatbot.
 *
 * Retrieval uses LOCAL TF-IDF embeddings (no external embedding API needed), so the
 * bot works with just a Groq key. The answer is generated by Groq's chat model with
 * streaming. Chunks are precomputed into data/docsChunks.json by scripts/buildDocsIndex.ts
 * (also using local embeddings), and rebuilt on the fly if missing.
 *
 * Needs: GROQ_API_KEY (or GROQ_API_KEY env) in the backend .env.
 */
import fs from "node:fs";
import path from "node:path";
import { RecursiveCharacterTextSplitter } from "@langchain/textsplitters";
import { ChatGroq } from "@langchain/groq";

const dataDir = path.resolve(process.cwd(), "data");
const chunksPath = path.join(dataDir, "docsChunks.json");

type Chunk = { id: string; text: string; embedding: number[] };

let chunksCache: Chunk[] | null = null;

/* ── Local TF-IDF embeddings (dimension-free, sparse → dense via vocab index) ── */
const STOP = new Set(
  "the a an and or to of in for on with your you is are be this that it as from by if not can will our no at we use using when how what which into out up their them then than so do does did has have s t can't don't should must may might".split(
    " ",
  ),
);

function tokenize(text: string): string[] {
  return (text.toLowerCase().match(/[a-z0-9_]+/g) ?? []).filter(
    (t) => t.length > 1 && !STOP.has(t),
  );
}

let VOCAB: string[] = [];
const vocabIndex = new Map<string, number>();

function buildVocab(chunks: { text: string }[]) {
  const df = new Map<string, number>();
  for (const c of chunks) {
    for (const t of new Set(tokenize(c.text))) df.set(t, (df.get(t) ?? 0) + 1);
  }
  // Keep the most informative terms (filter very rare + ultra common), cap size.
  VOCAB = [...df.entries()]
    .filter(([, n]) => n >= 1)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 4000)
    .map(([t]) => t);
  VOCAB.forEach((t, i) => vocabIndex.set(t, i));
}

function embed(text: string): number[] {
  const dim = VOCAB.length || 1;
  const vec = new Array(dim).fill(0);
  const N = chunksCache?.length || 1;
  const lines = text.split("\n");
  // Tokens on the heading line (# Section) are weighted higher so queries that
  // name a section (e.g. "Express") match the right chunk, not a false substring.
  lines.forEach((line, li) => {
    const weight = li === 0 ? 3 : 1;
    for (const t of tokenize(line)) {
      const i = vocabIndex.get(t);
      if (i === undefined) continue;
      const idf = Math.log((1 + N) / (1 + (documentFrequency.get(t) ?? 1))) + 1;
      vec[i] += idf * weight;
    }
  });
  // L2 normalize
  let norm = 0;
  for (const v of vec) norm += v * v;
  norm = Math.sqrt(norm) || 1;
  return vec.map((v) => v / norm);
}

const documentFrequency = new Map<string, number>();

function computeDF(chunks: { text: string }[]) {
  documentFrequency.clear();
  for (const c of chunks) {
    for (const t of new Set(tokenize(c.text))) {
      documentFrequency.set(t, (documentFrequency.get(t) ?? 0) + 1);
    }
  }
}

function cosineSimilarity(a: number[], b: number[]): number {
  let dot = 0;
  for (let i = 0; i < a.length; i++) dot += a[i] * b[i];
  return dot;
}

/**
 * Section-aware chunking: split the markdown on `## ` headings first so each
 * top-level section becomes its own dense chunk, then sub-split oversized
 * sections with the recursive splitter. This keeps related content (e.g. the
 * Express example) together for much better retrieval relevance.
 */
async function splitDocs(markdown: string): Promise<string[]> {
  const splitter = new RecursiveCharacterTextSplitter({
    chunkSize: 700,
    chunkOverlap: 80,
    separators: ["\n\n", "\n", ". ", " "],
  });

  // Two-level split: first on `## ` sections, then on `### ` sub-sections, so
  // each chunk can be tagged with its SPECIFIC heading (e.g. "Express", not just
  // "Frameworks"). That lets retrieval disambiguate sibling frameworks.
  const sections = markdown.split(/\n## /);
  const out: string[] = [];

  const pushSection = async (body: string, fallbackHeading: string) => {
    const headingMatch = body.match(/^##(?:#)?\s+(.+)$/m);
    const heading = headingMatch ? headingMatch[1].trim() : fallbackHeading;

    const subParts = body.split(/\n### /);
    for (let j = 0; j < subParts.length; j++) {
      const sub = (j === 0 ? subParts[j] : `### ${subParts[j]}`).trim();
      if (!sub) continue;
      const subHeadingMatch = sub.match(/^###\s+(.+)$/m);
      const subHeading = subHeadingMatch ? subHeadingMatch[1].trim() : heading;

      if (sub.length <= 700) {
        out.push(`# ${subHeading}\n${sub}`);
        continue;
      }
      const docs = await splitter.createDocuments([sub]);
      docs.forEach((d) => out.push(`# ${subHeading}\n${d.pageContent.trim()}`));
    }
  };

  for (let i = 0; i < sections.length; i++) {
    const body = (i === 0 ? sections[i] : `## ${sections[i]}`).trim();
    if (body) await pushSection(body, "");
  }
  return out;
}

async function ensureChunks(): Promise<Chunk[]> {
  if (chunksCache) return chunksCache;

  let texts: string[];
  if (fs.existsSync(chunksPath)) {
    const raw = JSON.parse(fs.readFileSync(chunksPath, "utf-8")) as Chunk[];
    texts = raw.map((c) => c.text);
  } else {
    const mdPath = path.join(dataDir, "docs.md");
    const markdown = fs.readFileSync(mdPath, "utf-8");
    texts = await splitDocs(markdown);
    const raw = texts.map((text, i) => ({ id: `chunk-${i}`, text, embedding: [] }));
    fs.writeFileSync(chunksPath, JSON.stringify(raw, null, 2));
  }

  const docs = texts.map((text) => ({ text }));
  computeDF(docs);
  buildVocab(docs);
  chunksCache = docs.map((d, i) => ({ id: `chunk-${i}`, text: d.text, embedding: embed(d.text) }));
  return chunksCache;
}

/** Returns the top-k most relevant chunks for a query. */
export async function retrieve(query: string, k = 4): Promise<string> {
  const chunks = await ensureChunks();
  const qVec = embed(query);
  const qTokens = new Set(tokenize(query));

  const ranked = chunks
    .map((c) => {
      let score = cosineSimilarity(qVec, c.embedding);
      // Heading-match bonus: a query term that names a section (e.g. "express",
      // "next", "errors") strongly signals the right chunk, disambiguating
      // sibling frameworks that share body vocabulary.
      const heading = c.text.split("\n")[0].replace(/^#\s*/, "").toLowerCase();
      const headingTokens = new Set(tokenize(heading));
      for (const t of qTokens) {
        if (headingTokens.has(t) && t.length > 2) score += 0.6;
      }
      return { text: c.text, score };
    })
    .sort((a, b) => b.score - a.score)
    .slice(0, k);
  return ranked.map((r) => r.text).join("\n\n---\n\n");
}

const SYSTEM_PROMPT = `You are the UploadAura documentation assistant. Answer the user's question using ONLY the provided documentation excerpts. Be concise and practical. If the answer isn't in the excerpts, say you don't know and suggest checking the full docs. Include short code snippets when relevant. Never invent APIs or options that aren't shown.`;

/** Streams the model's reply token-by-token via an async generator. */
export async function* streamAnswer(question: string): AsyncGenerator<string> {
  const context = await retrieve(question);
  const apiKey = process.env.GROQ_API_KEY;
  if (!apiKey) {
    yield "Docs assistant is not configured (missing GROQ_API_KEY).";
    return;
  }

  const model = new ChatGroq({
    apiKey,
    model: "llama-3.3-70b-versatile",
    streaming: true,
    temperature: 0.2,
  });

  const stream = await model.stream([
    ["system", SYSTEM_PROMPT].join("\n\n"),
    `Documentation:\n${context}`,
    `Question: ${question}`,
  ]);

  for await (const chunk of stream) {
    const text = chunk.content?.toString?.() ?? "";
    if (text) yield text;
  }
}
